# Generated by Django 3.2.12 on 2023-06-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogenericviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.DeleteModel(
            name='ContactFile',
        ),
    ]
