# Generated by Django 3.2.12 on 2023-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogenericviews', '0002_auto_20230620_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='djangogenericviews.contactfile'),
        ),
    ]
