# Generated by Django 3.2.12 on 2023-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogenericviews', '0003_auto_20230620_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactFile',
        ),
    ]
