# Generated by Django 3.2.12 on 2023-06-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogenericviews', '0004_auto_20230620_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='files',
        ),
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents/')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='djangogenericviews.contact')),
            ],
        ),
    ]
