# Generated by Django 3.2.12 on 2023-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogenericviews', '0005_auto_20230620_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactfile',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
