# Generated by Django 3.2.12 on 2023-07-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'delivered'), (3, 'shipped'), (2, 'ready for shipment'), (1, 'Not packed')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ManyToManyField(to='mastering_django.UserType'),
        ),
    ]
