# Generated by Django 3.2.12 on 2023-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0006_auto_20230712_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerManager',
        ),
        migrations.DeleteModel(
            name='SellerManager',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'delivered'), (2, 'ready for shipment'), (1, 'Not packed'), (3, 'shipped')], default=1),
        ),
    ]
