# Generated by Django 3.2.12 on 2023-07-18 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0008_auto_20230712_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Phone number must consist of 10 digits', regex='^\\d{10}$')])),
                ('query', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'shipped'), (4, 'delivered'), (1, 'Not packed'), (2, 'ready for shipment')], default=1),
        ),
    ]
