# Generated by Django 3.2.12 on 2023-07-20 09:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0010_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default=[], max_length=255, verbose_name='default types'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'shipped'), (1, 'Not packed'), (4, 'delivered'), (2, 'ready for shipment')], default=1),
        ),
    ]
