# Generated by Django 3.2.12 on 2023-08-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0011_auto_20230720_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mastering_django/productimages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (3, 'shipped'), (2, 'ready for shipment'), (4, 'delivered')], default=1),
        ),
    ]
