# Generated by Django 3.2.12 on 2023-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering_django', '0014_auto_20230804_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (3, 'shipped'), (4, 'delivered'), (2, 'ready for shipment')], default=1),
        ),
    ]
